"""Record-free structural scene-builder visual inputs; no scientific record admission."""

from collections.abc import Mapping
from typing import Protocol


class VisualRenderPlan(Protocol):
    @property
    def rgba_by_surface(self) -> Mapping[str, str]: ...
    @property
    def material_by_surface(self) -> Mapping[str, str]: ...
    @property
    def asset_bytes(self) -> Mapping[str, bytes]: ...
    @property
    def asset_xml(self) -> str: ...
    @property
    def light_direction(self) -> str: ...
    @property
    def light_diffuse(self) -> str: ...
    @property
    def light_ambient(self) -> str: ...
