"""Annotation exports; pure raster derivation does not import native apparatus."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from epsbench.annotations.derive import (
    classify_mask_changes,
    derive_boundary_structure,
    derive_visibility,
)

__all__ = [
    "AFTER_EVENT_CODE_DOMAIN",
    "ANALYTIC_BOUNDARY_RULE",
    "ANALYTIC_BOUNDARY_WIDTH_PIXELS",
    "ANALYTIC_SURFACE_INTERSECTION_RULE",
    "ANALYTIC_TRANSPORT_METHOD",
    "ATTACHMENT_CONTACT_MANIFOLD_RULE",
    "ATTACHMENT_CONTACT_TOLERANCE",
    "ATTACHMENT_EDGE_ASSOCIATION_RULE",
    "ATTACHMENT_ENDPOINT_TIE_RULE",
    "ATTACHMENT_FEASIBILITY_RULE",
    "ATTACHMENT_IMAGE_FEASIBILITY_SLACK",
    "ATTACHMENT_IMAGE_TOLERANCE_PIXELS",
    "ATTACHMENT_MULTI_SURFACE_RULE",
    "ATTACHMENT_PROJECTION_CONVENTION",
    "ATTACHMENT_PROJECTION_IN_FRONT_RULE",
    "ATTACHMENT_PUBLIC_CONTRACT_VERSION",
    "ATTACHMENT_ROTATION_TOLERANCE",
    "ATTACHMENT_RULE",
    "BEFORE_EVENT_CODE_DOMAIN",
    "BOUNDARY_KIND_DOMAIN",
    "COUNTERFACTUAL_CONTINUATION_RULE",
    "COUNTERFACTUAL_TIE_RULE",
    "EDGE_LATTICE_CONVENTION",
    "FINITE_PLANE_EDGE_BINARY64_EPSILON",
    "FINITE_PLANE_EDGE_COMPARISON_RULE",
    "FINITE_PLANE_EDGE_MINIMUM_TOLERANCE_SCALE",
    "FINITE_PLANE_EDGE_TOLERANCE_MULTIPLIER",
    "FINITE_PLANE_EXTENT_RULE",
    "FLOW_FIXED_POINT_SCALE",
    "FLOW_QUANTISATION_ROUNDING",
    "JUNCTION_AMBIGUITY_RULE",
    "ORIENTED_BOUNDARY_METHOD",
    "OWNER_SIDE_DOMAIN",
    "RAY_DIRECTION_EPSILON",
    "SILHOUETTE_RULE",
    "SUPPORTED_CONTACT_MANIFOLD_TYPES",
    "TARGET_VISIBILITY_RULE",
    "VISIBILITY_EVENT_METHOD",
    "VISIBILITY_MINIMUM_TOLERANCE_SCALE",
    "VISIBILITY_RELATIVE_TOLERANCE",
    "AfterOriginCode",
    "AnalyticCamera",
    "AnalyticTransportArrays",
    "BeforeFateCode",
    "DirectionalTransportArrays",
    "RawBoundaryVisibilityAnalysis",
    "TransportReasonCode",
    "analytic_boundary_ambiguity",
    "classify_mask_changes",
    "classify_oriented_boundary_lattice",
    "compute_analytic_transport",
    "compute_raw_boundary_visibility_analysis",
    "counterfactual_surface_assignments",
    "derive_boundary_structure",
    "derive_visibility",
    "focal_scales_from_vertical_fov",
    "pixel_rays_world",
    "project_world_points",
    "projected_attachment_locus_edges",
    "validate_analytic_camera",
    "verify_attachment_contract",
]

if TYPE_CHECKING:
    from epsbench.annotations.boundary_events import (
        AFTER_EVENT_CODE_DOMAIN,
        ATTACHMENT_CONTACT_MANIFOLD_RULE,
        ATTACHMENT_CONTACT_TOLERANCE,
        ATTACHMENT_EDGE_ASSOCIATION_RULE,
        ATTACHMENT_ENDPOINT_TIE_RULE,
        ATTACHMENT_FEASIBILITY_RULE,
        ATTACHMENT_IMAGE_FEASIBILITY_SLACK,
        ATTACHMENT_IMAGE_TOLERANCE_PIXELS,
        ATTACHMENT_MULTI_SURFACE_RULE,
        ATTACHMENT_PROJECTION_CONVENTION,
        ATTACHMENT_PROJECTION_IN_FRONT_RULE,
        ATTACHMENT_PUBLIC_CONTRACT_VERSION,
        ATTACHMENT_ROTATION_TOLERANCE,
        ATTACHMENT_RULE,
        BEFORE_EVENT_CODE_DOMAIN,
        BOUNDARY_KIND_DOMAIN,
        COUNTERFACTUAL_CONTINUATION_RULE,
        COUNTERFACTUAL_TIE_RULE,
        EDGE_LATTICE_CONVENTION,
        JUNCTION_AMBIGUITY_RULE,
        ORIENTED_BOUNDARY_METHOD,
        OWNER_SIDE_DOMAIN,
        SILHOUETTE_RULE,
        SUPPORTED_CONTACT_MANIFOLD_TYPES,
        VISIBILITY_EVENT_METHOD,
        AfterOriginCode,
        BeforeFateCode,
        RawBoundaryVisibilityAnalysis,
        classify_oriented_boundary_lattice,
        compute_raw_boundary_visibility_analysis,
        projected_attachment_locus_edges,
        verify_attachment_contract,
    )
    from epsbench.annotations.optical_transport import (
        ANALYTIC_BOUNDARY_RULE,
        ANALYTIC_BOUNDARY_WIDTH_PIXELS,
        ANALYTIC_SURFACE_INTERSECTION_RULE,
        ANALYTIC_TRANSPORT_METHOD,
        FINITE_PLANE_EDGE_BINARY64_EPSILON,
        FINITE_PLANE_EDGE_COMPARISON_RULE,
        FINITE_PLANE_EDGE_MINIMUM_TOLERANCE_SCALE,
        FINITE_PLANE_EDGE_TOLERANCE_MULTIPLIER,
        FINITE_PLANE_EXTENT_RULE,
        FLOW_FIXED_POINT_SCALE,
        FLOW_QUANTISATION_ROUNDING,
        RAY_DIRECTION_EPSILON,
        TARGET_VISIBILITY_RULE,
        VISIBILITY_MINIMUM_TOLERANCE_SCALE,
        VISIBILITY_RELATIVE_TOLERANCE,
        AnalyticCamera,
        AnalyticTransportArrays,
        DirectionalTransportArrays,
        TransportReasonCode,
        analytic_boundary_ambiguity,
        compute_analytic_transport,
        counterfactual_surface_assignments,
        focal_scales_from_vertical_fov,
        pixel_rays_world,
        project_world_points,
        validate_analytic_camera,
    )

_NATIVE_EXPORTS = {
    "epsbench.annotations.boundary_events": (
        "AFTER_EVENT_CODE_DOMAIN",
        "ATTACHMENT_CONTACT_MANIFOLD_RULE",
        "ATTACHMENT_CONTACT_TOLERANCE",
        "ATTACHMENT_EDGE_ASSOCIATION_RULE",
        "ATTACHMENT_ENDPOINT_TIE_RULE",
        "ATTACHMENT_FEASIBILITY_RULE",
        "ATTACHMENT_IMAGE_FEASIBILITY_SLACK",
        "ATTACHMENT_IMAGE_TOLERANCE_PIXELS",
        "ATTACHMENT_MULTI_SURFACE_RULE",
        "ATTACHMENT_PROJECTION_CONVENTION",
        "ATTACHMENT_PROJECTION_IN_FRONT_RULE",
        "ATTACHMENT_PUBLIC_CONTRACT_VERSION",
        "ATTACHMENT_ROTATION_TOLERANCE",
        "ATTACHMENT_RULE",
        "BEFORE_EVENT_CODE_DOMAIN",
        "BOUNDARY_KIND_DOMAIN",
        "COUNTERFACTUAL_CONTINUATION_RULE",
        "COUNTERFACTUAL_TIE_RULE",
        "EDGE_LATTICE_CONVENTION",
        "JUNCTION_AMBIGUITY_RULE",
        "ORIENTED_BOUNDARY_METHOD",
        "OWNER_SIDE_DOMAIN",
        "SILHOUETTE_RULE",
        "SUPPORTED_CONTACT_MANIFOLD_TYPES",
        "VISIBILITY_EVENT_METHOD",
        "AfterOriginCode",
        "BeforeFateCode",
        "RawBoundaryVisibilityAnalysis",
        "classify_oriented_boundary_lattice",
        "compute_raw_boundary_visibility_analysis",
        "projected_attachment_locus_edges",
        "verify_attachment_contract",
    ),
    "epsbench.annotations.optical_transport": (
        "ANALYTIC_BOUNDARY_RULE",
        "ANALYTIC_BOUNDARY_WIDTH_PIXELS",
        "ANALYTIC_SURFACE_INTERSECTION_RULE",
        "ANALYTIC_TRANSPORT_METHOD",
        "FINITE_PLANE_EDGE_BINARY64_EPSILON",
        "FINITE_PLANE_EDGE_COMPARISON_RULE",
        "FINITE_PLANE_EDGE_MINIMUM_TOLERANCE_SCALE",
        "FINITE_PLANE_EDGE_TOLERANCE_MULTIPLIER",
        "FINITE_PLANE_EXTENT_RULE",
        "FLOW_FIXED_POINT_SCALE",
        "FLOW_QUANTISATION_ROUNDING",
        "RAY_DIRECTION_EPSILON",
        "TARGET_VISIBILITY_RULE",
        "VISIBILITY_MINIMUM_TOLERANCE_SCALE",
        "VISIBILITY_RELATIVE_TOLERANCE",
        "AnalyticCamera",
        "AnalyticTransportArrays",
        "DirectionalTransportArrays",
        "TransportReasonCode",
        "analytic_boundary_ambiguity",
        "compute_analytic_transport",
        "counterfactual_surface_assignments",
        "focal_scales_from_vertical_fov",
        "pixel_rays_world",
        "project_world_points",
        "validate_analytic_camera",
    ),
}


def __getattr__(name: str) -> Any:
    for module, names in _NATIVE_EXPORTS.items():
        if name in names:
            value = getattr(import_module(module), name)
            globals()[name] = value
            return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
