"""Ecological-oracle annotation derivation."""

from epsbench.annotations.derive import (
    classify_mask_changes,
    derive_boundary_structure,
    derive_visibility,
)
from epsbench.annotations.optical_transport import (
    ANALYTIC_BOUNDARY_RULE,
    ANALYTIC_BOUNDARY_WIDTH_PIXELS,
    ANALYTIC_SURFACE_INTERSECTION_RULE,
    ANALYTIC_TRANSPORT_METHOD,
    FINITE_PLANE_EDGE_BINARY64_EPSILON,
    FINITE_PLANE_EDGE_COMPARISON_RULE,
    FINITE_PLANE_EDGE_MINIMUM_TOLERANCE_SCALE,
    FINITE_PLANE_EDGE_TOLERANCE_MULTIPLIER,
    FINITE_PLANE_EXTENT_RULE,
    FLOW_FIXED_POINT_SCALE,
    FLOW_QUANTISATION_ROUNDING,
    RAY_DIRECTION_EPSILON,
    TARGET_VISIBILITY_RULE,
    VISIBILITY_MINIMUM_TOLERANCE_SCALE,
    VISIBILITY_RELATIVE_TOLERANCE,
    AnalyticCamera,
    AnalyticTransportArrays,
    DirectionalTransportArrays,
    TransportReasonCode,
    analytic_boundary_ambiguity,
    compute_analytic_transport,
    focal_scales_from_vertical_fov,
    pixel_rays_world,
    project_world_points,
)

__all__ = [
    "ANALYTIC_BOUNDARY_RULE",
    "ANALYTIC_BOUNDARY_WIDTH_PIXELS",
    "ANALYTIC_SURFACE_INTERSECTION_RULE",
    "ANALYTIC_TRANSPORT_METHOD",
    "FINITE_PLANE_EDGE_BINARY64_EPSILON",
    "FINITE_PLANE_EDGE_COMPARISON_RULE",
    "FINITE_PLANE_EDGE_MINIMUM_TOLERANCE_SCALE",
    "FINITE_PLANE_EDGE_TOLERANCE_MULTIPLIER",
    "FINITE_PLANE_EXTENT_RULE",
    "FLOW_FIXED_POINT_SCALE",
    "FLOW_QUANTISATION_ROUNDING",
    "RAY_DIRECTION_EPSILON",
    "TARGET_VISIBILITY_RULE",
    "VISIBILITY_MINIMUM_TOLERANCE_SCALE",
    "VISIBILITY_RELATIVE_TOLERANCE",
    "AnalyticCamera",
    "AnalyticTransportArrays",
    "DirectionalTransportArrays",
    "TransportReasonCode",
    "analytic_boundary_ambiguity",
    "classify_mask_changes",
    "compute_analytic_transport",
    "derive_boundary_structure",
    "derive_visibility",
    "focal_scales_from_vertical_fov",
    "pixel_rays_world",
    "project_world_points",
]
